### ISSUE TITLE
How to Re Scan LGTM through dashboard

### ISSUE THREAD

**Issue by matt212** [Semmle/SecurityQueries#9]
Hi , 
I am unable to find options to **re run scan** for dashboard it seems it only run scan  once  when we attach the repo first time 
![LGTM](https://user-images.githubusercontent.com/1698139/183058878-42d3d2a5-0d26-4dd8-833c-b0c87d879479.png)
however when we perform PR to merge in master those are reflected on separate tab not on main dashboard screen !
![LGTM-pr](https://user-images.githubusercontent.com/1698139/183059124-c453961f-63d6-4044-9985-9069ecf74536.png)

basically the ask here is there should be options to re run or even reflect the changes of PR merge in main lgtm dashboard screen !

**Comment by MathiasVP** [comment]
Hi @matt212,

Thank you for raising this issue. This isn't currently possible on LGTM, unfortunately. However, note that LGTM will poll your default branch for new commits each day. So once the PR is merged, and the next poll happens, the main alerts page will update automatically.

Have you considered switching to [GitHub Code Scanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning) instead? You should get the same analysis results, and most likely a better overall experience!

As you may have noticed, there isn't a lot of activity on this repository anymore. Therefore, I'll close this issue. If you want to continue this discussion feel free to open an issue on the [CodeQL repository](https://github.com/github/codeql).
